### PR TITLE
Fix status computation for runs

### LINKED ISSUE #2: Wrong job durations
Job durations are not computed properly by the webapp, they are displayed to be much longer than they really are.

### PR DESCRIPTION
**Pull request by pnmadelaine**
The build should not be counted as part of a run's duration, since builds are cached and it could have started and finished before the run even started. Also, a sub-task being canceled does not mean that the entire run was canceled: for instance, the "end" action will still be triggered after a canceled build.

Closes: #2

### CODE REVIEW

File: typhon-types/src/task_status.rs [hunk 1]
```diff
@@ -172,16 +172,30 @@ impl core::cmp::Ord for TaskStatusKind {
...
+                TaskStatusKind::Pending
+            }
+            (
+                Some(TaskStatusKind::Success),
+                Some(TaskStatusKind::Success),
+                Some(TaskStatusKind::Success),
+            ) => TaskStatusKind::Success,
+            _ => TaskStatusKind::Error,
+        };
+        kind.into_task_status(start, end)
```
Comment (W95Psp) [inline typhon-types/src/task_status.rs:198]: What if the `start` action takes a long time while the `build` action and the `end` action finish before?
This would produce a wrong status I believe.

Also, the case `Canceled` is not handled, is that on purpose?

Comment (pnmadelaine) [reply typhon-types/src/task_status.rs:198]: The "end" action waits for both the build the "begin" action to finish before starting, so no risk for a wrong status.

Currently a run can't be properly canceled, as it is not internally represented as a task. Once it is, this code will be obsolete anyway…

Comment (W95Psp) [reply typhon-types/src/task_status.rs:198]: Ah, nice! Yeah, makes sense :)

**Review by W95Psp — APPROVED** [review]
