### PR TITLE
fix(core): store settings in a `OnceCell` instead of a `Lazy`

### LINKED ISSUE #7: `typhon_core::SETTINGS` should be a `OnceCell`, not a `Lazy`
Currently, `typhon_core::SETTINGS` is a lazy whose initializer relies on an environment variable.
`typhon::main` first sets the environment variable then the lazy initializes `typhon_core::SETTINGS` using this env variable.
We should not rely on environment variable to pass state. Instead we should use a `OnceCell` and initialize it in `typhon::main`.

### PR DESCRIPTION
**Pull request by W95Psp**
Closes: #7

### CODE REVIEW

**Review by pnmadelaine — CHANGES_REQUESTED** [review]
Definitely a good improvement of the code, but I find the use of the term "state" confusing. Settings don't change over time and are not part of what I would refer to as the state of Typhon.

File: typhon-core/src/lib.rs [hunk 1]
```diff
@@ -42,14 +42,31 @@ use diesel::prelude::*;
 use diesel::r2d2;
 use diesel_migrations::{embed_migrations, EmbeddedMigrations, MigrationHarness};
 use futures_core::stream::Stream;
-use once_cell::sync::Lazy;
+use once_cell::sync::{Lazy, OnceCell};
 use serde::{Deserialize, Serialize};
 
+/// Global settings for Typhon. `Settings::init` is expected to be
+/// called exactly once to initialize the state, then `Settings::get`
+/// retrieve the state.
```
Comment (pnmadelaine) [inline typhon-core/src/lib.rs:50]:
```suggestion
/// Global settings for Typhon. `Settings::init` is expected to be called
/// exactly once for initialization, then `Settings::get` can be used to
/// retrieve the data.
```

File: typhon-core/src/lib.rs [hunk 2]
```diff
@@ -42,14 +42,31 @@ use diesel::prelude::*;
...
+        fn get() -> &'static Self {
+            STATE.get().expect("Settings were not initialized")
+        }
+        fn init(settings: Self) {
+            STATE
+                .set(settings)
+                .expect("Settings were already initalized")
+        }
+    }
+};
```
Comment (pnmadelaine) [inline typhon-core/src/lib.rs:68]:
```suggestion
const _: () = {
    static CELL: OnceCell<Settings> = OnceCell::new();
    impl Settings {
        fn get() -> &'static Self {
            CELL.get().expect("Settings were not initialized")
        }
        fn init(settings: Self) {
            CELL
                .set(settings)
                .expect("Settings were already initalized")
        }
    }
};
```

**Review by pnmadelaine — APPROVED** [review]
